### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by mapogox** [Echo-Ji/STDEN#1]
您好，请问可以分享一下数据集吗

**Comment by mrdmh** [comment]
> 

你好，请问你有数据集了吗

**Comment by mapogox** [comment]
> 

没呢

**Comment by Echo-Ji** [comment]
你们好，非常欢迎专注我们的文章 👏 

数据集为项目合作的内容，由于保密原因暂时不能公开 😩 

不过我们正在向合作单位申请数据公开权限，届时会公开一个更大的数据集，敬请关注 🚀
